
const genText = document.getElementById("gen-text")

var myMusic =
  document.getElementById("music");

genText.addEventListener("click", function () {
  let messages = [
    "Every time I see you, I can’t help but smile",
"You have this way of making everything better just by being around",
"Your smile is honestly the best part of my day",
"I can’t stop thinking about how amazing you look everyday",
"I don’t know how you manage to look so good every time I see you",
"Is it just me, or do you get more beautiful every time I see you",
"You make my heart race without even trying",
"You’re like sunshine on a cloudy day",
"Talking to you makes my day a hundred times better",
"Your laughter is my favorite sound",
"How do you always look so perfect",
"I think you might be responsible for the butterflies in my stomach",
"I can’t help but smile when I see your name pop up",
"You’re so beautiful, it’s almost unreal",
"You’ve got a way of making everything seem effortless",
"I don’t know how you do it, but you always manage to take my breath away",
"Can you stop being so perfect? It’s distracting",
"Every time I see you, my heart skips a beat",
"You’ve got this charm that I can’t quite explain",
"Is it just me, or do you make even the smallest moments feel extraordinary",
"Can’t stop thinking about how cute you are",
"You must be a dream, because you’re too perfect to be real",
"I still can’t believe someone as amazing as you exists",
"You’re my favorite distraction",
"I bet the stars are jealous of how much you shine",
"You’re the highlight of my day every time I see you",
"Your smile is my new favorite thing in the world",
"I could get lost in your eyes forever",
"You’re like the sweetest dream I never want to wake up from",
"I always get excited when I see your name pop up",
"I will step on very spiders for you hehe",
"I can’t help but feel so happy when I’m around you",
"Every time I see you, I just want to be near you more",
"I can’t even find the right words to explain how amazing you are",
"Every moment with you is like a gift I don’t deserve",
"You have this way of making everything feel more beautiful",
"I’m not sure if it’s your smile or your eyes, but you’ve totally got my attention",
"I don’t know what it is, but you always leave me speechless",
"Can you just stop being so cute? It’s making it hard to focus",
"I don’t think you realize how much you brighten my day",
"You’ve got this magical presence that I can’t get enough of",
"You make my heart race every time you walk into a room",
"You’re the kind of person who could turn any bad day into something amazing",
"You make me feel things I never knew I could feel",
"Your beauty is honestly breathtaking",
"I could stare at you all day and never get bored",
"I’m pretty sure my heart beats faster every time I see you",
"You’ve definitely got my full attention",
"I love everything about you, from your smile to your amazing personality",
"Talking to you always puts me in the best mood",
"Just thinking about you makes my day instantly better",
"You’ve got this way of making everything around you more amazing",
"I think you might be the most beautiful person I’ve ever seen",
"You’ve got this incredible energy that’s so hard to resist",
"How are you even real? You’re too perfect",
"I think about you more than I care to admit",
"I can’t get enough of your smile",
"You make my heart skip a beat every time you smile",
"You make my heart race in the best way possible",
"I’m pretty sure I could get lost in your eyes forever",
"I don’t know what it is, but I can’t stop thinking about you",
"Whenever I see you, it feels like everything else fades away",
"You have no idea how often I find myself thinking about you",
"Honestly, every time I see you, my heart just skips a beat",
"I’ll never get tired of seeing you smile",
"Every moment with you is like living in a dream",
"You're the reason I can’t stop smiling",
  ]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor(Math.random() * messages.length)]
  myMusic.play();
})